<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 4 sp1 (x64) (http://www.altova.com) by Christopher Kardos (private) -->
<wsdl:definitions xmlns:tns="http://iec.ch/TC57/2017/ExecuteEndDeviceControls" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:infoMessage="http://iec.ch/TC57/2017/EndDeviceControlsMessage" name="ExecuteEndDeviceControls" targetNamespace="http://iec.ch/TC57/2017/ExecuteEndDeviceControls">
	<wsdl:types>
		<xs:schema targetNamespace="http://iec.ch/TC57/2017/ExecuteEndDeviceControls" elementFormDefault="qualified">
			<xs:import namespace="http://iec.ch/TC57/2017/EndDeviceControlsMessage" schemaLocation="xsd/EndDeviceControlsMessage.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="CreateEndDeviceControlsRequestMessage">
		<wsdl:part name="CreateEndDeviceControlsRequestMessage" element="infoMessage:CreateEndDeviceControls"/>
	</wsdl:message>
	<wsdl:message name="ResponseMessage">
		<wsdl:part name="ResponseMessage" element="infoMessage:EndDeviceControlsResponseMessage"/>
	</wsdl:message>
	<wsdl:message name="FaultMessage">
		<wsdl:part name="FaultMessage" element="infoMessage:EndDeviceControlsFaultMessage"/>
	</wsdl:message>
	<wsdl:portType name="EndDeviceControls_Port">
		<wsdl:operation name="CreateEndDeviceControls">
			<wsdl:input name="CreateEndDeviceControlsRequest" message="tns:CreateEndDeviceControlsRequestMessage"/>
			<wsdl:output name="CreateEndDeviceControlsResponse" message="tns:ResponseMessage"/>
			<wsdl:fault name="CreateEndDeviceControlsFault" message="tns:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="EndDeviceControls_Binding" type="tns:EndDeviceControls_Port">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CreateEndDeviceControls">
			<soap:operation soapAction="http://iec.ch/TC57/2017/EndDeviceControls/CreateEndDeviceControls" style="document"/>
			<wsdl:input name="CreateEndDeviceControlsRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="CreateEndDeviceControlsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="CreateEndDeviceControlsFault">
				<soap:fault name="CreateEndDeviceControlsFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ExecuteEndDeviceControls">
		<wsdl:port name="EndDeviceControls_Port" binding="tns:EndDeviceControls_Binding">
			<soap:address location="http://localhost:8088/mockEndDeviceControls"/>
		</wsdl:port>
	</wsdl:service>
	<xs:schema targetNamespace="http://iec.ch/TC57/2017/ExecuteEndDeviceControlsMessage" elementFormDefault="qualified">
		<xs:import namespace="http://iec.ch/TC57/2017/EndDeviceControlsMessage" schemaLocation="xsd/EndDeviceControlsMessage.xsd"/>
		<!--<xs:include schemaLocation="xsd/EndDeviceControlsMessage.xsd"/>-->
	</xs:schema>
</wsdl:definitions>
